### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lambtron** [lambtron/tipper-scan#1]
- [x] setup basic app (bot structure)
- [x] pull followers from new mongoDB of just twitter handles. maybe do this every day? hour? figure out how to refresh.
- [x] if tweet matches followers and '$' (or whatever) then parse tweet and add to jobs queue
- [x] parsing tweet: `@andyjiang $20 for turkey sandwich` => `{ amount: 2000, receiver: @andyjiang, sender: @blah }`

**Comment by lambtron** [comment]
- [x] research jobs queue
- [x] add jobs queue
- [x] jobs queue should also probably delete duplicates (we'll just run staggered scanners to add new followers)
